name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run build
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Run export
        uses: borales/actions-yarn@v4
        with:
          cmd: export

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
      